### PR TITLE
slovak.locale

### PR DESCRIPTION
**Pull request by Pr0metheus2**

### CODE REVIEW

**Comment by svenhoefer** [comment]
Hey, Andrej.

Can you please rework this pull request?
Commit f3558fb contains the ful languagefile. That isn't necessary. And again ... please don't re-add the Neutrino-HD string to single languagefiles. ;)

Commit d2616e2 is OK, but i don't know any way to merge this single commit from your pull request.

Thanks to your collaboration on Neutrino.

Regards, Sven.

**Comment by Pr0metheus2** [comment]
Hi Sven,
I don't know exactly how this updating through Github works. Don't know how to do it exactly, I am loosing here. If you can explain little bit how to do it properly.
Thank you.

**Comment by Pr0metheus2** [comment]
You can ignore commit f3558fb, it's already included in commit d2616e2. But I need explanation to understand the way how it works.

**Comment by svenhoefer** [comment]
>>> If you can explain little bit how to do it properly.
That's simple. 

Use 'git pull' to update your own repo. Than do your changes and commit these changes with 'git commit'. Push it to your repo with 'git push' and start the pull request. So your repo is always in sync with tuxbox-repo.

Your yesterdays second try was fine.

**Comment by Pr0metheus2** [comment]
Thanks, I was doing it online through github.com.
See you.

**Pull request closed without merging**
