### PR TITLE
Update slovak.locale

### PR DESCRIPTION
**Pull request by Pr0metheus2**
New update, is it submitted in correct way?

### CODE REVIEW

**Comment by Pr0metheus2** [comment]
Hi, I've made online update in Coolstream Tank, file **HD2_update.bin Version 122** from 19.01.2017, but slovak.locale was not updated and I have still old localization file. Slovak.locale should be updated automatically as well, I am right?

**Comment by Ezak91** [comment]
with what bs did you create the update?
I think you need neutrino_full.bin with bs4cs

**Comment by Pr0metheus2** [comment]
I did not build anything myself. Maybe I am wrong, but I think all changes are every time applied into new builds available online though receiver menu - Update from network. Or?

Here is example what I see when I search for new update:

http://www.Cool-Stream.to/wwwupdate/HD2_update/20170110-1937-GIT-Ver.-381-8543HD2_update.bin A302201701101937 45767e85d3881c065715e759097fc717 HD2_update.bin Version 120
http://www.Cool-Stream.to/wwwupdate/HD2_update/20170111-1613-GIT-Ver.-382-8544HD2_update.bin A302201701111613 a0894b6faa1a38dc947c800e93fa64b0 HD2_update.bin Version 121
http://www.Cool-Stream.to/wwwupdate/HD2_update/20170119-1540-GIT-Ver.-383-8550HD2_update.bin A302201701191540 c7f19c2744565bb60d67cf6cf3986c06 HD2_update.bin Version 122
http://www.Cool-Stream.to/wwwupdate/HD2_update/20170122-1840-GIT-Ver.-388-8553HD2_update.bin A302201701221840 8689a2a55e858e8db278c2a7f664319d HD2_update.bin Version 123 Driver Update V3

**Comment by svenhoefer** [comment]
I checked the linked packages.
The cool-stream.to guys did not include the languagefiles into their updates. :/
Please ask there to resolv this problem.

**Comment by Pr0metheus2** [comment]
OK, I will ask at their forum. Thanks for help.

**Pull request merged**
